# Generated by Django 5.2.6 on 2025-09-20 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=3, verbose_name='شماره کلاس')),
            ],
            options={
                'verbose_name_plural': 'کلاس',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=school.models.profile_img_upload_to, verbose_name='عکس پروفایل')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='سن')),
                ('user_type', models.CharField(choices=[('tch', 'teacher'), ('std', 'student'), ('prn', 'parent')], max_length=3, verbose_name='نوع کاربر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='سال روردی دانش آموز')),
                ('avg_1', models.PositiveIntegerField(default=0, verbose_name='معدل سال اول')),
                ('avg_2', models.PositiveIntegerField(default=0, verbose_name='معدل سال دوم')),
                ('avg_3', models.PositiveIntegerField(default=0, verbose_name='معدل سال سوم')),
                ('grade_level', models.CharField(choices=[('10', 'Grade_10'), ('11', 'Grade_11'), ('12', 'Grade_12')], max_length=2, verbose_name='پایه دانش آموز')),
                ('graduated', models.BooleanField(default=False, verbose_name='وضعیت فارغ التحصیلی')),
                ('current_student', models.BooleanField(default=True, verbose_name='دانش آموز فعلی')),
                ('extra_detail', models.CharField(blank=True, null=True, verbose_name='اطلاعات اضافه')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.class', verbose_name='کلاس دانش آموز')),
            ],
            options={
                'verbose_name_plural': 'اکانت دانش آموز',
                'ordering': ['-entry'],
            },
        ),
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_detail', models.CharField(blank=True, null=True, verbose_name='اطلاعات اضافه')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to=settings.AUTH_USER_MODEL, verbose_name='والدین')),
                ('parent_of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='school.studentaccount')),
            ],
            options={
                'verbose_name_plural': 'والدین',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام درس')),
                ('student_grade', models.PositiveSmallIntegerField(default=0, verbose_name='نمره دانش آموز')),
                ('term_time', django_jalali.db.models.jDateField(default=django.utils.timezone.now)),
                ('update', django_jalali.db.models.jDateField(auto_now=True)),
                ('grade_level', models.CharField(choices=[('10', 'Grade_10'), ('11', 'Grade_11'), ('12', 'Grade_12')], max_length=2, verbose_name='پایه درس')),
                ('lesson_students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.studentaccount', verbose_name='دانش آموزان این درس')),
            ],
            options={
                'verbose_name_plural': 'درس',
            },
        ),
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'معلم',
            },
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='student_lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', through='school.Lesson', to='school.teacheraccount', verbose_name='درس های دانش آموز'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.teacheraccount', verbose_name='معلم این درس'),
        ),
        migrations.AddIndex(
            model_name='studentaccount',
            index=models.Index(fields=['-student'], name='school_stud_student_272f66_idx'),
        ),
    ]
