# Generated by Django 5.2.6 on 2025-09-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentaccount',
            options={'verbose_name_plural': 'اکانت والدین'},
        ),
        migrations.AlterModelOptions(
            name='studentaccount',
            options={'ordering': ['entry'], 'verbose_name_plural': 'اکانت دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacheraccount',
            options={'verbose_name_plural': 'اکانت معلم ها'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('mng', 'manager'), ('tch', 'teacher'), ('std', 'student'), ('prn', 'parent')], max_length=3, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_account', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'اکانت مدیر',
            },
        ),
    ]
