# Generated by Django 5.2.6 on 2025-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageraccount',
            name='id_manager',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='شناسه مدیر'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='id_student',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='شناسه دانش آموز'),
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='id_teacher',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='شناسه معلم'),
        ),
    ]
