# Generated by Django 5.2.6 on 2025-09-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_students',
            new_name='lesson_student',
        ),
    ]
