# Generated by Django 5.2.6 on 2025-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='parentaccount',
            name='extra_detail',
            field=models.CharField(blank=True, null=True, verbose_name='اطلاعات اضافه'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='extra_detail',
            field=models.CharField(blank=True, null=True, verbose_name='اطلاعات اضافه'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.lesson'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.teacheraccount', verbose_name='معلم های دانش آموز'),
        ),
        migrations.AlterField(
            model_name='teacheraccount',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='school.lesson'),
        ),
    ]
