# Generated by Django 5.2.6 on 2025-09-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_parentaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentterm',
            options={'ordering': ['term_teacher'], 'verbose_name_plural': 'سال تحصیلی دانش آموز'},
        ),
        migrations.RemoveIndex(
            model_name='studentterm',
            name='school_stud_lesson__6b4666_idx',
        ),
        migrations.RemoveField(
            model_name='studentterm',
            name='lesson_student',
        ),
        migrations.RemoveField(
            model_name='studentterm',
            name='lesson_teacher',
        ),
        migrations.AddField(
            model_name='studentterm',
            name='term_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='school.studentaccount', verbose_name='دانش آموز این درس'),
        ),
        migrations.AddField(
            model_name='studentterm',
            name='term_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term', to='school.teacheraccount', verbose_name='معلم این درس'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_term',
            field=models.ManyToManyField(blank=True, related_name='students', through='school.StudentTerm', through_fields=('term_student', 'term_teacher'), to='school.teacheraccount', verbose_name='درس های دانش آموز'),
        ),
        migrations.AddIndex(
            model_name='studentterm',
            index=models.Index(fields=['term_teacher', 'term_lesson'], name='school_stud_term_te_87ece4_idx'),
        ),
    ]
