# Generated by Django 5.2.6 on 2025-09-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_manageraccount_id_manager_studentaccount_id_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='student_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='school.parentaccount', verbose_name='والد دانش آموز'),
        ),
    ]
