# Generated by Django 5.2.6 on 2025-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_user_options_alter_parentaccount_extra_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='student_teachers',
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='student_teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.teacheraccount'),
        ),
    ]
