# Generated by Django 5.2.6 on 2025-09-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_studentaccount_student_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='student_lessons',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='student_teacher',
        ),
        migrations.RemoveField(
            model_name='teacheraccount',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='school.studentaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ForeignKey(default='null_yet', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_lessons', to='school.teacheraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_grade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='نمره دانش آموز'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='student_lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', through='school.Lesson', to='school.teacheraccount'),
        ),
    ]
