# Generated by Django 5.2.6 on 2025-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_studentaccount_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='id_student',
            field=models.PositiveIntegerField(default=0, verbose_name='شناسه دانش آموز'),
        ),
    ]
