# Generated by Django 5.2.6 on 2025-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_studentaccount_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='id_student',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='شناسه دانش آموز'),
        ),
    ]
