# Generated by Django 5.2.6 on 2025-09-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_studentaccount_student_lessons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentaccount',
            old_name='student_lesson',
            new_name='student_lessons',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.studentaccount'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.teacheraccount'),
        ),
    ]
