# Generated by Django 5.2.6 on 2025-09-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_studentaccount_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentterm',
            name='term_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_student', to='school.studentaccount', verbose_name='دانش آموز این درس'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='term_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_teacher', to='school.teacheraccount', verbose_name='معلم این درس'),
        ),
    ]
