# Generated by Django 5.2.6 on 2025-10-02 13:06

import django.db.models.deletion
import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_studentterm_term_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='توضیحات عکس')),
                ('image', models.ImageField(upload_to=school.models.school_news_img_description_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('title_image', models.ImageField(upload_to=school.models.school_news_title_img_upload_to)),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('description_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_news', to='school.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('true', 'Checked'), ('false', 'Not checked')], default='false', max_length=5, verbose_name='وضعیت')),
                ('response', models.CharField(max_length=1000, verbose_name='پاسخ معلم')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tickets', to='school.parentaccount', verbose_name='والد')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tickets', to='school.teacheraccount', verbose_name='معلم')),
            ],
        ),
    ]
