# Generated by Django 5.2.6 on 2025-10-05 15:57

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_imagemodel_schoolnews_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolnews',
            options={'ordering': ['date'], 'verbose_name_plural': 'اخبار دبیرستان'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status'], 'verbose_name_plural': 'پیام'},
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AddIndex(
            model_name='schoolnews',
            index=models.Index(fields=['date'], name='school_scho_date_ad02d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='school_tick_status_d4ef5d_idx'),
        ),
    ]
