# Generated by Django 5.2.6 on 2025-10-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolnews_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolnews',
            name='description_image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='school.schoolnews', verbose_name='خبر'),
        ),
    ]
