# Generated by Django 5.2.6 on 2025-10-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_schoolnews_description_image_imagemodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='school.schoolnews', verbose_name='خبر'),
        ),
    ]
