# Generated by Django 5.2.6 on 2025-10-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_imagemodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_image', to='school.schoolnews', verbose_name='خبر'),
        ),
    ]
