# Generated by Django 5.2.6 on 2025-10-11 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_imagemodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='avg_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='معدل سال اول'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='avg_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='معدل سال دوم'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='avg_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='معدل سال سوم'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='student_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='نمره دانش آموز'),
        ),
    ]
