# Generated by Django 5.2.6 on 2025-10-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_studentaccount_avg_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='student_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='school.parentaccount', verbose_name='والد دانش آموز'),
        ),
    ]
