# Generated by Django 5.2.6 on 2025-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_studentaccount_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentterm',
            name='active_term',
            field=models.BooleanField(default=True, verbose_name='فعال بودن ترم'),
        ),
    ]
