# Generated by Django 5.2.6 on 2025-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_studentterm_active_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='پاسخ معلم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('mng', 'مدیر'), ('tch', 'معلم'), ('std', 'دانش آموز'), ('prn', 'والد')], max_length=3, verbose_name='نوع کاربر'),
        ),
    ]
