# Generated by Django 5.2.6 on 2025-12-17 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_ticket_response_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='schoolnews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='entry',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='سال روردی دانش آموز'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='term_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
