# Generated by Django 5.2.6 on 2025-12-17 21:16

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_lesson_update_alter_schoolnews_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='update',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='schoolnews',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='entry',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='سال روردی دانش آموز'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='term_time',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='update',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
