# Generated by Django 5.2.6 on 2025-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_lesson_update_alter_schoolnews_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentterm',
            options={'ordering': ['term_teacher'], 'permissions': [('can_change_score', 'Can set and change student scores')], 'verbose_name_plural': 'سال تحصیلی دانش آموزان'},
        ),
    ]
