# Generated by Django 5.2.6 on 2025-12-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_studentterm_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status'], 'permissions': [('teacher_response', 'Allows teachers to give respone to parents tickets'), ('parent_ticket', 'Can send tickets to teachers')], 'verbose_name_plural': 'پیام'},
        ),
    ]
