# Generated by Django 5.2.6 on 2025-12-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_studentterm_options'),
    ]

    operations = [
    ]
