# Generated by Django 5.2.6 on 2025-12-19 17:53

from django.db import migrations

def create_groups_and_permissions(apps, schema_editor):
    '''
    Creating groups and giving permissions to them
    '''

    # getting essential models (we can't import models in a migration file)
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # creating groups
    teachers_group, _ = Group.objects.get_or_create(name="Teachers")
    parents_group, _ = Group.objects.get_or_create(name="Parents")

    # getting needed models from models.py if you wnat to use 
    # .get_for_model(model name)
    # StudentTerm = apps.get_model("school", "StudentTerm")
    # Ticket = apps.get_model("school", "Ticket")

    # getting models content types
    studentterm_contenttype = ContentType.objects.get(app_label="school", model="studentterm")
    ticket_contenttype = ContentType.objects.get(app_label="school", model="ticket")

    # getting model permissions usin content type
    studentterm_permissions = Permission.objects.filter(
        content_type=studentterm_contenttype, codename='can_change_score')
    ticket_permissions = Permission.objects.filter(
        content_type=ticket_contenttype, codename__in=['teacher_response', 'parent_ticket'])

    # giving groups permissions
    teachers_group.permissions.set(studentterm_permissions, ticket_permissions.get(codename='teacher_response'))
    parents_group.permissions.set(ticket_permissions.get(codename='parent_ticket'))

def assigning_users_to_groups(apps, schema_editor):

    # fetching needed models
    Group = apps.get_model("auth", "Group")
    Users = apps.get_model("school", "User")

    # getting teacher and parent users
    teachers = Users.objects.filter(user_type='tch')
    parents = Users.objects.filter(user_type='prn')

    # getting needed groups
    teachers_group = Group.objects.get(name='Teachers')
    parents_group = Group.objects.get(name='Parents')

    # addind teachers and parents to their groups
    for teacher in teachers:
        teacher.groups.add(teachers_group)

    for parent in parents:
        parent.groups.add(parents_group)
    
class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_ticket_options'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, migrations.RunPython.noop),
        migrations.RunPython(assigning_users_to_groups, migrations.RunPython.noop)
    ]
